In [34]:
import numpy as np
import os
from PIL import Image, ImageOps
from matplotlib import pyplot as plt
from scipy import signal

In [35]:
path = '/Users/harrisonward/Desktop/CS/Git/pixelator/assets'
gscale1 = "$@B%8&WM#*oahkbdpqwmZO0QLCJUYXzcvunxrjft/\|()1{}[]?-_+~<>i!lI;:,\"^`'. "

In [36]:
# store lazily rendered images
images = []
for file in os.listdir(path):
    fname, ftype = file.split('.')
    if fname != '' and ftype == 'jpeg':
        print(file)
        images.append(Image.open(f'{path}/{file}'))

IMG_2012.jpeg
IMG_8737.jpeg
IMG_8740.jpeg
_DSC6014.jpeg
FullSizeRender.jpeg


In [37]:
def avg_brightness(image_array):
    return int(np.average(image_array, axis=None))

In [38]:
def convert_to_gs(image_array):
    return np.mean(np.asarray(image_array), axis=2)

Find the image array dimensions

In [73]:
def img_to_ascii(image, n_cols, scale):
    output_image = []
    slice_cordinates = []

    image_array = convert_to_gs(np.array(image)).T

    W, H = image_array.shape

    # tile width
    w = W / n_cols

    # tile height 
    h = w / scale

    n_rows = int(H/h)

    print(f"cols: {n_cols}, rows: {n_rows}")
    print(f"tile dims: {w} x {h}")

    for i in range(n_rows):
        
        # pixel number times tile height
        y1 = int(i * h)
        
        # pixel one to the right
        # could probably add a % to handle the wrap around
        y2 = int((i+1)*h)

        if i == n_rows - 1:
            y2 = H

        # add an empty string 
        output_image.append("")

        for j in range(n_cols):
            # x tile is the pixel number times the tile width
            x1 = int(j*w)
            x2 = int((j+1)*w)

            if i == n_cols - 1:
                x2 = W
            
            # crop the image, get the tile 
            # could also take a slice of the matrix at these indicies
            slice_cordinates.append([(x1, x2), (y1,y2)])
            tile = image_array[x1:x2, y1:y2]

            # get the average brightness
            avg = avg_brightness(tile)

            # look up ascii char
            gsval = gscale1[int((avg*69)/255)]

            # append the char 
            output_image[i] += gsval
    
    print(np.array(slice_cordinates))
    return output_image


In [74]:
def main(image, n_cols, scale):
    output_image = img_to_ascii(image, n_cols, scale)
    
    print('generating ASCII art...')
    
    # convert image to ascii txt
    outFile = 'out.txt'
 
    # open file
    f = open(outFile, 'w')
 
    # write to file
    for row in output_image:
        f.write(row + '\n')
 
    # cleanup
    f.close()
    print("ASCII art written to %s" % outFile)

In [75]:
main(images[2], n_cols=200, scale=0.43)

cols: 200, rows: 91
tile dims: 4.395 x 10.220930232558139
[[[  0   4]
  [  0  10]]

 [[  4   8]
  [  0  10]]

 [[  8  13]
  [  0  10]]

 ...

 [[865 870]
  [919 933]]

 [[870 874]
  [919 933]]

 [[874 878]
  [919 933]]]
generating ASCII art...
ASCII art written to out.txt
